// @ts-ignore - generated by `npx convex dev`
import { query } from "./_generated/server";
import { v } from "convex/values";

export const listActive = query({
  args: {
    role: v.union(
      v.literal("driver"),
      v.literal("owner"),
      v.literal("client"),
      v.literal("corporate"),
      v.literal("all")
    ),
  },
  returns: v.array(
    v.object({
      _id: v.id("ads"),
      _creationTime: v.number(),
      title: v.string(),
      description: v.optional(v.string()),
      imageUrl: v.optional(v.string()),
      targetRole: v.union(
        v.literal("driver"),
        v.literal("owner"),
        v.literal("client"),
        v.literal("corporate"),
        v.literal("all")
      ),
      isActive: v.boolean(),
      startDate: v.optional(v.number()),
      endDate: v.optional(v.number()),
      createdAt: v.number(),
    })
  ),
  handler: async (ctx, args) => {
    const now = Date.now();
    const allAds = await ctx.db
      .query("ads")
      .withIndex("by_target_role", (q) =>
        q.eq("targetRole", args.role === "all" ? "all" : args.role)
      )
      .collect();

    return allAds.filter((ad) => {
      if (!ad.isActive) return false;
      if (ad.startDate && ad.startDate > now) return false;
      if (ad.endDate && ad.endDate < now) return false;
      return true;
    });
  },
});

export const listAllForAdmin = query({
  args: {},
  returns: v.array(
    v.object({
      _id: v.id("ads"),
      _creationTime: v.number(),
      title: v.string(),
      description: v.optional(v.string()),
      imageUrl: v.optional(v.string()),
      targetRole: v.union(
        v.literal("driver"),
        v.literal("owner"),
        v.literal("client"),
        v.literal("corporate"),
        v.literal("all")
      ),
      isActive: v.boolean(),
      startDate: v.optional(v.number()),
      endDate: v.optional(v.number()),
      createdAt: v.number(),
    })
  ),
  handler: async (ctx) => {
    return await ctx.db.query("ads").collect();
  },
});
