// @ts-ignore - generated by `npx convex dev`
import { query } from "./_generated/server";
import { v } from "convex/values";

export const listActive = query({
  args: {},
  returns: v.array(
    v.object({
      _id: v.id("referralCodes"),
      _creationTime: v.number(),
      code: v.string(),
      description: v.optional(v.string()),
      discountPercent: v.optional(v.number()),
      isActive: v.boolean(),
      createdAt: v.number(),
      expiresAt: v.optional(v.number()),
    })
  ),
  handler: async (ctx) => {
    const now = Date.now();
    return await ctx.db
      .query("referralCodes")
      .withIndex("by_code")
      .collect()
      .then((codes) =>
        codes.filter(
          (code) =>
            code.isActive &&
            (code.expiresAt === undefined || code.expiresAt > now)
        )
      );
  },
});
