// @ts-ignore - generated by `npx convex dev`
import { action, mutation, query } from "./_generated/server";
import { api } from "./_generated/api";
import { v } from "convex/values";
import { Id } from "./_generated/dataModel";

type VerificationStatus = "not_started" | "capturing" | "processing" | "review" | "confirmed" | "failed" | "pending_review";

function stripBase64Prefix(value: string): string {
  return value.replace(/^data:image\/[a-zA-Z+]+;base64,/, "");
}

export const submitDocumentVerification = action({
  args: {
    userId: v.id("users"),
    documentType: v.string(),
    idNumber: v.string(),
    email: v.string(),
    address: v.string(),
    documentFront: v.string(),
    documentBack: v.optional(v.string()),
    selfie: v.optional(v.string()),
  },
  returns: v.object({
    referenceId: v.optional(v.string()),
    status: v.string(),
    confidence: v.optional(v.number()),
    raw: v.optional(v.any()),
  }),
  handler: async (ctx, args) => {
    const appId = process.env.DOJAH_APP_ID;
    const secretKey = process.env.DOJAH_SECRET_KEY;
    const environment = process.env.DOJAH_ENVIRONMENT ?? "sandbox";

    if (!appId || !secretKey) {
      throw new Error("Missing Dojah credentials in Convex env");
    }

    const baseUrl =
      environment === "production"
        ? "https://api.dojah.io"
        : "https://sandbox.dojah.io";

    const body: Record<string, string> = {
      input_type: "base64",
      imagefrontside: stripBase64Prefix(args.documentFront),
    };

    if (args.documentBack) {
      body.imagebackside = stripBase64Prefix(args.documentBack);
    }

    const response = await fetch(`${baseUrl}/api/v1/document/analysis`, {
      method: "POST",
      headers: {
        AppId: appId,
        Authorization: secretKey,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`Dojah document analysis failed: ${response.status} ${text}`);
    }

    const data = (await response.json()) as any;

    const overallStatus = data?.entity?.status?.overall_status;
    const status: VerificationStatus =
      overallStatus === 1 ? "confirmed" : "failed";

    const extractedFields = (data?.entity?.text_data ?? []) as Array<{
      field_key: string;
      value: string;
    }>;

    const extracted = extractedFields.reduce<Record<string, string>>(
      (acc, field) => {
        if (field.field_key && field.value) {
          acc[field.field_key] = field.value;
        }
        return acc;
      },
      {}
    );

    const referenceId = data?.entity?.id ?? data?.entity?.reference_id;

    await ctx.runMutation(api.verifications.recordVerification, {
      userId: args.userId,
      referenceId: referenceId ?? "",
      status,
      documentType: args.documentType,
      confidence: data?.entity?.status?.overall_status == null ? undefined : 100,
      livenessPassed: undefined,
    });

    return {
      referenceId,
      status,
      confidence: 100,
      raw: data,
    };
  },
});

export const checkDojahStatus = action({
  args: { referenceId: v.string() },
  returns: v.object({
    status: v.string(),
    confidence: v.optional(v.number()),
    livenessPassed: v.optional(v.boolean()),
    raw: v.optional(v.any()),
  }),
  handler: async (ctx, args) => {
    const appId = process.env.DOJAH_APP_ID;
    const secretKey = process.env.DOJAH_SECRET_KEY;
    const environment = process.env.DOJAH_ENVIRONMENT ?? "sandbox";

    if (!appId || !secretKey) {
      throw new Error("Missing Dojah credentials in Convex env");
    }

    const baseUrl =
      environment === "production"
        ? "https://api.dojah.io"
        : "https://sandbox.dojah.io";

    const response = await fetch(
      `${baseUrl}/api/v1/verification/${encodeURIComponent(args.referenceId)}`,
      {
        method: "GET",
        headers: {
          AppId: appId,
          SecretKey: secretKey,
          "Content-Type": "application/json",
        },
      }
    );

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`Dojah status check failed: ${response.status} ${text}`);
    }

    const data = (await response.json()) as any;

    let status: VerificationStatus = "processing";
    if (data?.status === "verified" || data?.verification_status === "verified") {
      status = "confirmed";
    } else if (data?.status === "rejected" || data?.verification_status === "rejected") {
      status = "failed";
    } else if (data?.status === "pending" || data?.verification_status === "pending") {
      status = "review";
    }

    return {
      status,
      confidence: data?.confidence ?? data?.match_confidence ?? undefined,
      livenessPassed: data?.liveness_passed ?? data?.liveness?.passed ?? undefined,
      raw: data,
    };
  },
});

export const recordVerification = mutation({
  args: {
    userId: v.id("users"),
    referenceId: v.string(),
    status: v.string(),
    documentType: v.optional(v.string()),
    confidence: v.optional(v.number()),
    livenessPassed: v.optional(v.boolean()),
  },
  returns: v.id("verifications"),
  handler: async (ctx, args) => {
    const now = Date.now();
    const existing = await ctx.db
      .query("verifications")
      .withIndex("by_user_id", (q) => q.eq("userId", args.userId))
      .first();

    if (existing) {
      await ctx.db.patch(existing._id, {
        status: args.status,
        documentType: args.documentType ?? existing.documentType,
        confidence: args.confidence ?? existing.confidence,
        livenessPassed: args.livenessPassed ?? existing.livenessPassed,
        updatedAt: now,
      });
      return existing._id;
    }

    return await ctx.db.insert("verifications", {
      userId: args.userId,
      documentType: args.documentType,
      status: args.status,
      confidence: args.confidence,
      livenessPassed: args.livenessPassed,
      createdAt: now,
      updatedAt: now,
    });
  },
});

export const getByUserId = query({
  args: { userId: v.id("users") },
  returns: v.union(
    v.object({
      _id: v.id("verifications"),
      _creationTime: v.number(),
      userId: v.id("users"),
      documentType: v.optional(v.string()),
      status: v.string(),
      livenessPassed: v.optional(v.boolean()),
      confidence: v.optional(v.number()),
      createdAt: v.number(),
      updatedAt: v.number(),
    }),
    v.null()
  ),
  handler: async (ctx, args) => {
    return await ctx.db
      .query("verifications")
      .withIndex("by_user_id", (q) => q.eq("userId", args.userId))
      .first();
  },
});
